# Generated by Django 4.2.1 on 2023-05-26 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_tb_articulos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tb_Articulos',
        ),
    ]
