# Generated by Django 4.2.1 on 2023-05-26 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_delete_tb_articulos'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_Articulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Articulo', models.IntegerField()),
                ('nom_Articulo', models.CharField(max_length=50)),
                ('desc_Articulo', models.TextField(max_length=500)),
            ],
        ),
    ]
